version: : "3"
  service:
    database:
      image: postgres:latest
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        - 'POSTGRES_HOST_AUTH_METHOD=true'

    api:
      build:
      volumes:
        - . :/infinitebazaar
      ports:
        - "7887:7887"
      command:
        - uvicorn
        - main:app
        - --host=0.0.0.0
        - --port=6969
      depends_on:
        - database
  volumes:
    postgres_data: